{% set name = "raynest" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/raynest-{{ version }}.tar.gz
  sha256: 7204ae01b22a04c622924773de4efe15711e6f3ffce8bd9e330525b89aba648a

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  # ray is not available on OSX yet
  skip: true  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
    - setuptools-scm
  run:
    - python
    - numpy
    - scipy
    - corner
    - tqdm
    - matplotlib-base
    - ray-default
    - dill
    - h5py

test:
  imports:
    - raynest
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wdpozzo/raynest
  summary: 'raynest: Parallel nested sampling based on ray'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
