{% set name = "raynest" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/raynest-{{ version }}.tar.gz
  sha256: 7d691dbd528f1c3290668d0a629ffd332adb98783fa6883548ef188d30baca17

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  # ray is not available on OSX yet
  skip: true  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools-scm
  run:
    - corner
    - cython
    - dill
    - h5py
    - matplotlib-base
    - psutil
    - python
    - ray-default
    - scipy
    - tqdm
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - raynest
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wdpozzo/raynest
  summary: 'raynest: Parallel nested sampling based on ray'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
